# set -ga terminal-overrides ",xterm-256color:Tc"
# set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"

set -g mouse on
set -g history-limit 20000
set -g base-index 1

# set -g status-right "%H:%M"
# set -g window-status-current-style "underscore"

bind-key -T copy-mode C-w send-keys -X copy-pipe 'xsel -ib'
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xsel -ib'

# set -g set-titles on                                    # Разрешить смену заголовков в оконном менеджере
# set -g set-titles-string "tmux.#I.#W"                   # Формат строки заголовка

set -g bell-action any                                  # Следить за активностью на всех окнах

setw -g monitor-activity on                             # Информировать когда есть активность в окнах
set -g visual-activity on                               # Показывать статусное сообщение при активности в каком либо окне

bind-key k confirm kill-window                          # Подтверждать уничтожение окна
bind-key K confirm kill-server                          # Подтверждать уничтожение сервера

set -g display-time 2000                                # Время в миллисекундах, сколько будут отображаться сообщения (в статусбаре к примеру)

# Цвета статусбара
# set -g status-fg white
# set -g status-bg default

set-option -g repeat-time 0

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-window-option -g mode-keys vi
setw -g mode-keys vi

bind-key -n M-Enter copy-mode

bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind-key -T copy-mode-vi  Up     send-keys  -X  cursor-up
bind-key -T copy-mode-vi  Down   send-keys  -X  cursor-down

bind-key -T copy-mode-vi  Home  send-keys  -X  back-to-indentation
bind-key -T copy-mode-vi  End   send-keys  -X  end-of-line

bind-key -T copy-mode-vi y send-keys -X copy-pipe 'xsel -ib'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xsel -ib'

# set -g status-right '#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)'

bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"
